# Generated by Django 5.1 on 2025-02-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayclass',
            name='boundEducationHours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayclass',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dayclass',
            name='learningHours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayclass',
            name='trainingHours',
            field=models.IntegerField(default=0),
        ),
    ]
