# Generated by Django 5.1 on 2025-02-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dayclass_boundeducationhours_dayclass_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayclass',
            old_name='learningHours',
            new_name='dayLearningHours',
        ),
        migrations.AddField(
            model_name='dayclass',
            name='nightLearningHours',
            field=models.IntegerField(default=0),
        ),
    ]
