# Generated by Django 5.1 on 2025-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_interval_monthsdata_alter_interval_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='weekStart',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='interval',
            name='monthsData',
            field=models.JSONField(default=[{'endDate': '2025-03-03', 'startDate': '2025-02-02'}, {'endDate': '2025-04-02', 'startDate': '2025-03-04'}, {'endDate': '2025-05-02', 'startDate': '2025-04-03'}, {'endDate': '2025-06-01', 'startDate': '2025-05-03'}, {'endDate': '2025-07-01', 'startDate': '2025-06-02'}, {'endDate': '2025-07-31', 'startDate': '2025-07-02'}, {'endDate': '2025-08-06', 'startDate': '2025-08-01'}]),
        ),
    ]
