# Generated by Django 5.1 on 2025-02-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_interval_weekstart_alter_interval_monthsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.IntegerField()),
                ('persentage', models.IntegerField()),
                ('day', models.BooleanField()),
                ('night', models.BooleanField()),
            ],
        ),
    ]
