# Generated by Django 5.1 on 2025-02-11 23:30

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='types',
            field=models.JSONField(default=api.utils.default_months_data),
        ),
        migrations.AlterField(
            model_name='interval',
            name='data',
            field=models.JSONField(default=api.utils.default_interval),
        ),
        migrations.AlterField(
            model_name='interval',
            name='monthsData',
            field=models.JSONField(default=api.utils.default_months_data),
        ),
    ]
