# Generated by Django 5.1 on 2025-02-11 23:33

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_interval_types_alter_interval_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='types',
            field=models.JSONField(default=api.utils.default_types),
        ),
    ]
