# Generated by Django 5.1 on 2025-02-15 15:06

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_interval_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subjects', models.JSONField(verbose_name=api.utils.default_jobs)),
            ],
        ),
    ]
