# Generated by Django 5.1 on 2025-02-16 19:32

import api.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='subjects',
            field=models.JSONField(default=api.utils.default_jobs),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=250)),
                ('training_tools', models.CharField(max_length=250)),
                ('teacher', models.CharField(max_length=250)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
    ]
