# Generated by Django 5.1 on 2025-02-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_job_subjects_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='night',
            field=models.BooleanField(default=False),
        ),
    ]
