# Generated by Django 5.1 on 2025-02-16 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_topic_day_topic_night'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='teacher',
            new_name='instructor',
        ),
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_class',
            field=models.CharField(default='فرد', max_length=150),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.subject'),
        ),
    ]
