# Generated by Django 5.1 on 2025-01-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(default=0, verbose_name='صلاحية الحساب'),
        ),
    ]
